namespace Sycade.BunqApi.Model.NotificationFilters
{
    public enum NotificationFilterCategory
    {
        BILLING,
        CARD_TRANSACTION_SUCCESSFUL,
        CARD_TRANSACTION_FAILED,
        CHAT,
        DRAFT_PAYMENT,
        FRIEND_SIGN_UP,
        IDEAL,
        MONETARY_ACCOUNT_PROFILE,
        SOFORT,
        MUTATION,
        PAYMENT,
        PROMOTION,
        REQUEST,
        SCHEDULE_RESULT,
        SCHEDULE_STATUS,
        SHARE,
        SLICE_CHAT,
        SLICE_REGISTRY_ENTRY,
        SLICE_REGISTRY_MEMBERSHIP,
        SLICE_REGISTRY_SETTLEMENT,
        SUPPORT,
        TAB_RESULT,
        USE_RESPONSE,
        USER_APPROVAL,
        WHITELIST,
        WHITELIST_RESULT
    }
}
